AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Saml template for Nexus jobs with lambdas
Globals:
  Function:
    Tags:
      env: dev
Parameters:
  LambdaRole:
    Type: String
    Default: arn:aws:iam::052257736952:role/Lambda
Resources:
  CheckS3encryption:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "com-ebi-nx-s3-check-encryption"
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: "To Check the S3 bucket encryption"
      MemorySize: 128
      Timeout: 30
      Role: !Ref LambdaRole
      Events:
        CWSchedule:
            Properties:
              EventPattern:
                source:
                  - "aws.events"
            Type: Schedule
CWSchedule:
  Type: Schedule
  Properties:
    Schedule: 'rate(1 minute)'
    Name: S3encryptionSchedule
    Description: To trigger lambda function
    Enabled: true
